language: php

matrix:
  include:
    - php: 5.5
      env: PHP_VER=5
    - php: 5.6
      env: PHP_VER=5
    - php: 7.0
      env: PHP_VER=7
    - php: nightly
      env: PHP_VER=7

install:
  - composer install --no-interaction --prefer-dist

script:
  # use vendor phpunit
  - sh -c "./vendor/bin/phpunit"
  - sh -c "./vendor/bin/phpcs --standard=PSR2 ./src/"

services:
  - redis-server